### PR TITLE
Normalize whitespace, style, python3 print compatability for quick start

### PR DESCRIPTION
**Pull request by JordanRushing**
In order to improve my understanding of YANN for the creation of better-designed testing I embarked through your quick-start documentation [here](https://yann.readthedocs.io/en/master/index.html#quick-start) and implemented these changes as I went.

### CODE REVIEW

**Comment by ragavvenkatesan** [comment]
I am just about to make a big commit today. I am migrating from regular batchnorm to theano's new batchnorm. I am also migrating from dnn to libgpuarray backed completely. I will merge your request after I make this commit.

**Comment by JordanRushing** [comment]
Thank you!

**Comment by ragavvenkatesan** [comment]
@JordanRushing , I created a Project in this repo for you to update todos, plans and milestones on.

**Comment by ragavvenkatesan** [comment]
This looks good. I don't think you have changed anything that will affect the toolbox's working. I will make the commit I am working on now first, then I will merge yours to the master. I will merge yours to test branch at the moment.

**Comment by JordanRushing** [comment]
@ragavvenkatesan , Excellent - thank you! We will utilize the project immediately.

**Comment by ragavvenkatesan** [comment]
@JordanRushing  I also opened an issue 'milestone' for you to keep track of. I've been asked by someone from University of California at San Diego who wants to chip in to the test module too, so in case they are going to, they can refer the project and the milestone.

**Pull request merged**
