### PR TITLE
Modify test_activations, remove whitespace, and begin Python3 support

### PR DESCRIPTION
**Pull request by chummm**
Modify test_activations.py to utilize unittest instead of pytest. Add hardcoded, expected results from activation functions that are precomputed to remove dependancy on class-method activation functions. Clean up whitespace from multiple files. Begin adding parenthesis around print statements for Python3 support.

### CODE REVIEW

**Comment by chummm** [comment]
Hey there! My name is Kyri Vanderpoel and I've been paid programming with Jordan Rushing, who you've already spoken with. I'm a software engineer in Texas with experience with test-driven development. I've been looking to get involved in machine learning and open source software, and YANN seems like an excellent way to put my testing skills to use while pursuing those goals. 

I'll start by working with Jordan to achieve full test coverage. I'd also like to get the project up to date for use with Python3, as well as get the style in line with PEP8. While that is happening, I should develop an understanding of how to use YANN and a high level understanding of machine learning. 

This commit removed unnecessary white space, fixed some style issues, and converted the activations tests to utilize the style of testing that I'm familiar with.

Thank you for an opportunity to work on this project. If you create a testing branch, we could commit to that instead of the master branch.

-Kyri

**Comment by ragavvenkatesan** [comment]
Kyri,

Wow, ok. Yann has so far been a private pet project of mine and a few of my colleagues. I use it in my deep learning course, so I haven't bothered really to write unittests. I do think that from its humble beginnings, Yann has grown into a proper toolbox now and needs collaborators to add to the module. I am glad you and @JordanRushing  are adding to the unittests. Thanks,

I will accept this PR in the master branch as I don't see this affecting the toolbox's functionality much. But I will create a test branch for you to merge onto from now on. 

Thanks,
R.

**Comment by ragavvenkatesan** [comment]
@chummm @JordanRushing ,

I have created a test branch to which you can PR. I will merge the test branch to master, whenever I can. 

Thanks,
R

**Comment by JordanRushing** [comment]
Ragav,

Thank you for the branch. YANN is a great project and we are very excited to contribute more.

Jordan

**Pull request merged**
